
vi playbooks/patching/06_datapatch_primary.yml
---
- name: Run Datapatch on New Primary
  hosts: primary
  become: yes
  become_user: oracle

  vars:
    oracle_env: /home/oracle/.bash_profile

  tasks:

    - name: Run datapatch
      shell: |
        . {{ oracle_env }} >/dev/null 2>&1
        cd $ORACLE_HOME/OPatch
        ./datapatch -verbose
      register: datapatch_result

    - name: Show datapatch output
      debug:
        msg: "{{ datapatch_result.stdout_lines }}"
        
+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++  
cd /home/naresh.sajwani/Learning/Ansible/oracle-ansible-dg-outofplace
ansible -i inventory/dataguard-prim-stby/ all -m ping
cat -A playbooks/patching/06_datapatch_primary.yml
ansible-playbook --syntax-check -i inventory/dataguard-prim-stby/ playbooks/patching/06_datapatch_primary.yml
ansible-playbook -i inventory/dataguard-prim-stby/ playbooks/patching/06_datapatch_primary.yml
       		        