---
- name: Run Datapatch on New Primary
  hosts: primary
  become: yes
  become_user: oracle

  vars:
    oracle_env: /home/oracle/.bash_profile

  tasks:

    - name: Run datapatch
      shell: |
        . {{ oracle_env }} >/dev/null 2>&1
        cd $ORACLE_HOME/OPatch
        ./datapatch -verbose
      register: datapatch_result

    - name: Show datapatch output
      debug:
        msg: "{{ datapatch_result.stdout_lines }}"       		        
